source/d4_calculation.f90, source/dftd4.f90
Calculation of atomic C8 coefficients for printout and printout of C8AA coefficients in property section.
=> added printout of C8AA coefficients

meson.build, meson_options.txt
=> allow more flexibility in the linear algebra backend

source/mctc_environment.f90
=> Bugfix: fixes faulty argparser logic :beetle:

README.md, python/README.md, python/dftd4/calculators.py
=> update documentation regarding Python-API

python/dftd4/interface.py, python/dftd4/utils.py
- fix C0415 warning for `dftd4.interface` and `dftd4.utils`
=> Pylint fixes

source/program_dftd.f90
=> read charge from `.CHRG` file

meson.build, source/dftd4.f90, tests/assertion.f90, tests/dftd4.f90, tests/tests_dftd.f90
The self interaction was scaled incorrectly (1 instead of 1/2). :beetle:
@f3rmion could you double check this?
=> Bugfix: i-i' interactions had wrong factor

meson.build, python/setup.py
- Bugfix: i->i' contribution is calculated correctly
=> Release 2.4.0 

source/dfuncpar.f90
=> added revDSD damping parameters

source/argparser.f90, source/geometry_reader.f90, source/program_dftd.f90
=> PBCs depend now only on geometry input

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/dco.yml, .github/workflows/fortran-build.yml, .travis.yml, README.md
=> update Travis CI workflow, add GH actions CI

README.md
now available at: https://anaconda.org/conda-forge/dftd4
=> add information about conda-forge package

meson.build, source/dfuncpar.f90
Closes #27.
See https://github.com/dftbplus/dftbplus/pull/314 for more details on the implementation of DFTB-D4.
=> Add D4 parameters for DFTB

meson.build, python/setup.py
=> bump version for release 2.5.0

man1/dftd4.1.txt
=> [doc] Remove duplicated `--version` from man

tests/dftd4.f90, tests/eeq_model.f90
Pointed out in: https://aur.archlinux.org/packages/dftd4/#comment-750446
=> Fix issues when building with GCC10

source/dftd4.f90
- include s9 in c9 coefficients for energy and gradient
=> Allow scaling of three body dispersion energy

source/dftd4.f90
- do-concurrent in OMP regions do not compile with Intel 20
=> Remove do-concurrent constructs from OMP regions

source/dftd4.f90
=> Reorder arithmetic operations to avoid float overflow (fix #52)

.github/workflows/fortran-build.yml, python/README.rst, python/dftd4/ase.py, python/dftd4/meson.build, python/dftd4/qcschema.py, python/dftd4/test_ase.py, python/setup.cfg
Closes https://github.com/dftd4/dftd4/issues/66
Closes https://github.com/dftd4/dftd4/issues/59
=> Implement ASE calculator for DFT-D4

.codecov.yml, .github/workflows/fortran-build.yml, README.md
Generate and upload coverage reports to codecov
=> Enable coverage analysis

.github/workflows/fortran-build.yml, fpm.toml, meson.build, python/dftd4/__init__.py, python/meson.build, python/setup.cfg, src/dftd4/version.f90
Next feature release of `dftd4`, mainly improvements on the API, added support for QCSchema and ASE.
=> Release version 3.1.0

app/main.f90, app/meson.build, app/tester.py
Useful for commandlines like
```
dftd4 --func r2scan --grad -- struc.xyz
```
=> Allow to terminate reading options with --

fpm.toml, meson.build, python/README.rst, python/dftd4/__init__.py, python/dftd4/ase.py, python/dftd4/libdftd4.py, python/dftd4/test_ase.py, python/meson.build, python/setup.cfg, src/dftd4/version.f90
=> Allow to add DFTD4 to other ASE calculators

python/dftd4/interface.py
See https://github.com/grimme-lab/xtb-python/issues/49
=> Use np.ascontiguousarray instead of np.array

.github/workflows/fortran-build.yml, src/dftd4/model.f90, src/dftd4/reference.f90, test/unit/test_model.f90
Required for self-consistent DFT-D4 calculations with GFN2-xTB.
=> Allow selection of reference charges

.github/workflows/fortran-build.yml, CMakeLists.txt, app/CMakeLists.txt, config/CMakeLists.txt, config/template.cmake, config/template.pc, src/CMakeLists.txt, src/dftd4/CMakeLists.txt, src/dftd4/damping/CMakeLists.txt, src/dftd4/data/CMakeLists.txt, subprojects/CMakeLists.txt, subprojects/mctc-lib.wrap, test/CMakeLists.txt, test/unit/CMakeLists.txt
Closes https://github.com/dftd4/dftd4/issues/93
=> Add support for CMake build system

README.md
=> Add information about dftd4 in spack

CMakeLists.txt, README.md, fpm.toml, meson.build, python/README.rst, python/dftd4/__init__.py, python/dftd4/libdftd4.py, python/setup.cfg, src/dftd4/version.f90, subprojects/mstore.wrap, subprojects/multicharge.wrap
- update mstore subproject to 0.2.0
- update multicharge subproject to 0.1.2
=> Bump version to 3.3.0

README.md
=> Add build instructions for CMake and fpm

config/meson.build, test/unit/meson.build
Some code simplification in the build system to allow better caching of dependencies in superbuilds
=> Update dependency handling in meson

README.md
https://www.freshports.org/science/dftd4
=> Add information on FreeBSD port

README.md, meson_options.txt, python/README.rst, python/dftd4/meson.build, python/meson_options.txt
See https://mesonbuild.com/Python-module.html#find_installation
=> Allow more flexible adjustment of Python version

config/cmake/dftd4-utils.cmake
https://cmake.org/cmake/help/v3.14/command/make_directory.html
=> replace deprecated `make_directory` with `file(MAKE_DIRECTORY)`

app/meson.build, config/meson.build, test/unit/meson.build
See https://github.com/grimme-lab/xtb/pull/640
Closes https://github.com/dftd4/dftd4/issues/161
=> Fix finding of MKL for Intel 2021 and newer

test/api/example.c
Test error condition in C-API explicitly.
=> Add error testing for C-API

CMakeLists.txt, README.md, doc/recipe/vasp.rst, fpm.toml, meson.build, python/README.rst, python/dftd4/__init__.py, python/dftd4/library.py, python/meson.build, python/mesonpep517.toml, python/setup.cfg, src/dftd4/version.f90
Merge once all issues on v3.5.0 milestone are resolved.
=> Bump to version 3.5.0

src/dftd4/api.f90
=> Delay creation of API object to avoid memory leak

include/dftd4.h, test/api/example.c
- prototype declarations
- initialize `error`
=> Minor fixes

python/dftd4/meson.build, python/dftd4/test_pyscf.py
Fixes failing wheel build on main branch.
=> Make Python installation pure: false by default

app/CMakeLists.txt, app/argument.f90, app/cli.f90, app/driver.f90, app/help.f90, app/meson.build, man/dftd4.1.adoc, src/dftd4/param.f90
=> Command line option for functional listing

.github/workflows/fortran-build.yml
See [here](https://github.com/mamba-org/provision-with-micromamba#example-1-environment-file-extra-specs-cache-env-semantic-versioning).
=> Update mamba provider

python/dftd4/pyscf.py
See https://github.com/pyscf/pyscf/issues/1986 and https://github.com/dftd3/simple-dftd3/pull/52
ping @sunqm
=> Update interface for gradient for PySCF 2.4

python/dftd4/pyscf.py, python/dftd4/test_pyscf.py
Same issue as https://github.com/dftd3/simple-dftd3/pull/74 and same fix ;)
=> Fix periodic PySCF calculations

CMakeLists.txt, README.md, config/cmake/Findcustom-blas.cmake, config/cmake/Findmctc-lib.cmake, config/cmake/Findmstore.cmake, config/cmake/Findmulticharge.cmake, doc/conf.py, doc/recipe/vasp.rst, fpm.toml, meson.build, python/README.rst, python/dftd4/__init__.py, python/dftd4/library.py, python/meson.build, python/pyproject.toml, src/dftd4/version.f90, subprojects/mctc-lib.wrap, subprojects/mstore.wrap, subprojects/multicharge.wrap
Probably needs to wait for #225 
Closes #255
=> Release version 3.7.0

.github/workflows/fortran-build.yml, config/meson.build, fpm.toml, test/unit/meson.build
Update and fix the fpm dependencies. Should be consistent among all projects for the xtb build.
=> Update and fix the dependencies in fpm

python/dftd4/parameters.py
See https://github.com/dftd3/simple-dftd3/pull/117.
=> Access parameters on Windows

src/dftd4/ncoord.f90, src/dftd4/output.f90, test/unit/test_dftd4.f90, test/unit/test_model.f90, test/unit/test_ncoord.f90, test/unit/test_periodic.f90
See https://github.com/dftd3/simple-dftd3/pull/77
=> Workarounds for Cray compilers

config/meson.build
See https://github.com/grimme-lab/xtb/pull/1133
=> Allow compilation without OpenMP for custom LAPACK

src/dftd4/damping/atm.f90, src/dftd4/damping/rational.f90, subprojects/.gitignore
See also https://github.com/grimme-lab/mctc-lib/pull/79 and https://github.com/grimme-lab/mctc-lib/pull/81.
=> Replace OMP reductions by thread-private variables + critical summation

.github/workflows/fortran-build.yml, assets/ci/build-env.yaml, assets/ci/python-env.yaml, assets/ci/wheel-req.txt, meson.build, python/meson.build, python/pyproject.toml
See https://github.com/mesonbuild/meson/issues/14528
See https://github.com/mesonbuild/meson/issues/14532
See https://github.com/mesonbuild/meson/pull/14549
=> Exclude meson version 1.8.0

.github/workflows/fortran-build.yml, .github/workflows/wheel.yml
Pins GCC 14 to avoid reported compilation errors with GCC 15. See https://github.com/grimme-lab/mctc-lib/issues/83.
=> Fix macOS workflows
