- source/class_molecule.f90
Typically, however, this worked since the loop had
incremented `j` to `i`.
> bug: fixed bug in array assignment

- dftd4.wrap
- meson.build
see [meson wrap](https://mesonbuild.com/Wrap-dependency-system-manual.html#wrapgit) for details.
> added wrap dependency file for dftd4

- source/c_api.f90
- `pure` has issues on some Linux distros with `c_loc`
> removed pure attribute in C-API

- python/dftd4/calculators.py
- python/dftd4/interface.py
- python/dftd4/test/test_calculators.py
- python/dftd4/test/test_interface.py
- python/dftd4/utils.py
- new interface wrapping the shared library
- more tests for interface
- python 3.5 compatibility
- OSX compatibility
> split ASE calculator from actual ctypes interface implementation

- source/d4_calculation.f90
`D4_calculation` was writing the strain derivatives of the EEQ to the dispersion strain derivatives :beetle: 
fixes this bug by using a temporary variable *and* initializing the energy, gradient and stress after EEQ and before calculation dispersion contributions.
> Bugfix: electrostatic stress was written to dispersion stress

- meson.build
Use workaround from https://github.com/mesonbuild/meson/issues/5374#issuecomment-497709445 to install Fortran module files.
> Install Fortran mod-files to include/ directory

- man1/dftd4.1.txt
- source/argparser.f90
- source/class_results.f90
- source/class_set.f90
- source/printout.f90
- source/program_dftd.f90
This allows to serialize all results from `dftd4` to JSON (flag: `--json`) or TOML (flag: `--toml`).
Fixes #37
> add JSON and TOML serialization for results type

- source/dfuncpar.f90
Add B97M and ωB97M parameters from https://onlinelibrary.wiley.com/doi/full/10.1002/jcc.26411, not adding ωB97X-D4 parameters due to already present parameters.
Also add B97-D parameters.
> Add damping parameters for B97M family

- source/mctc_strings.f90
- source/pbc_tools.f90
mctc_strings.f90(164): warning #8891: Specific names for intrinsic procedures are obsolescent in Fortran 2018.   [IABS]
pbc_tools.f90(367): warning #8891: Specific names for intrinsic procedures are obsolescent in Fortran 2018.   [IDNINT]
> Fix F2018 warnings seen with ifort

- meson.build
BSD date (eg. on macOS) does not support -I option
> Fix for BSD date

- source/dfuncpar.f90
See https://arxiv.org/abs/2012.09249
Also cleanup fitset statistics for B97M and ωB97M parameters
> Add D4 parameters for rSCAN and r²SCAN from arXiv:2012.09249

- .github/workflows/fortran-build.yml
- README.md
Create a bleeding edge release for new DFT-D4 version to allow easier testing. This feature is enabled on push, meaning developers enabling actions on their fork are able to use this workflow to create local versions of their branches.
> Enable continuous delivery of statically linked dftd4 versions

- README.md
- app/main.f90
Short option `-g` is no longer available
> Remove duplicated descriptions of --grad option and restore `-g`

- config/meson.build
- meson_options.txt
- subprojects/multicharge.wrap
- Python extension module must be linked against `mkl_rt` to work correctly with MKL
> Allow to link against mkl_rt library

- app/meson.build
- config/install-mod.py
- meson.build
- use the fact that only the dftd4 library is build at the toplevel
- find all module files in the toplevel directories in the build dir
> Add install script for module files

- README.md
- meson.build
- python/README.rst
- python/meson.build
Install script for module files requires at least 0.55.x
> Increase required meson version in documentation

- README.md
[README.md](https://github.com/dftd4/dftd4/blob/750b3ce4e838b1d7583ef1aa7652b59b7201c998/README.md) has the following relative links:
- &#91;&#96;&#96;dftd4(1)&#96;&#96;&#93;(man/dftd4.1.adoc)
- &#91;parameters.toml file&#93;(./assets/parameters.toml)
- &#91;&#96;&#96;python&#96;&#96;&#93;(./python)
These work on GitHub, but do not on https://dftd4.github.io/dftd4/, e.g., https://dftd4.github.io/dftd4/man/dftd4.1.adoc does not exist.
I’m not sure if ford can prefix https://github.com/dftd4/dftd4/blob/main/.
> Fix markdown and relative links on github.io page

- CMakeLists.txt
Needed for compilers which do not search the folder of the source file at file inclusion.
> Add missing include directive

- .github/workflows/fortran-build.yml
- README.md
- config/CMakeLists.txt
- fpm.toml
- meson_options.txt
- src/dftd4.f90
- src/dftd4/CMakeLists.txt
- src/dftd4/compat.f90
- src/dftd4/meson.build
Add updated `subdftd4.F` and mocked Vasp modules to test compilation.
Closes https://github.com/dftd4/dftd4/issues/85
Closes https://github.com/dftd4/dftd4_vasp/issues/3
> Add compatibility layer for integration with Vasp

- python/README.rst
- python/build.py
- python/setup.cfg
This should allow to install the Python API with pip using
```
pip install "https://github.com/dftd4/dftd4/archive/refs/heads/main#egg=dftd4-python&subdirectory=python"
```
It will require an existing `dftd4` installation, though. Chances for success can be improved by installing `pkgconfig`, setting `DFTD4_PREFIX` to the directory where the installation can be found or providing a C compiler in the `CC` environment variable. None of those are mandatory as we try to fall back to reasonable defaults, but those defaults might not be where `dftd4` is actually installed.
> Simplify Python setup process

- config/meson.build
- meson_options.txt
Fixes OpenBLAS finder and allows `-Dlapack=custom -Dcustom_libraries=blis,lapack`.
> Allow linking against custom linear algebra backend

- src/dftd4/model.f90
- also trap positive infinity when determining CN weights
Closes #127
> Better check for exceptional floating point values

- assets/parameters.toml
- src/dftd4/data/r4r2.f90
- src/dftd4/param.f90
- test/unit/test_param.f90
also update r4/r2 expectation values (see https://github.com/awvwgk/simple-dftd3/commit/5642677b691d2496ca7c8deca0ca85b1d56eddd8).
> Add parameters for r²SCAN hybrids

- config/cmake/Findmctc-lib.cmake
- config/cmake/Findmstore.cmake
- config/cmake/Findmulticharge.cmake
- config/cmake/dftd4-utils.cmake
I noticed that when mctc-lib, mstore and multicharge are fetched, cmake always fetched the head of the repository.
This patch adds some code to pin the fetched dependencies to the same versions specified in dftd4/subprojects/*.wrap
This helps make automated builds more reproducible, although it would be desirable to centralize versions in a single central file, or at least set them up as global CMake variables.
> pin fetched dependency versions in cmake build

- README.md
- include/dftd4.h
- meson.build
- test/api/example.c
- dispatch object handles to their respective deconstructor using _Generic
- automatically handle pass by reference of the object handle
> Add type generic macro for deleting API objects

- .github/workflows/wheel.yml
- assets/ci/wheel-req.txt
- python/mesonpep517.toml
Allows to build manylinux wheels for the Python bindings. Somewhat suboptimal since we have to redistribute OpenBLAS here, which makes the package huge (compared to a binary statically linked against MKL).
> Add workflow for building wheels

- config/cmake/Findcustom-blas.cmake
FindBLAS requires C or CXX to be enabled in order to use MKL.
https://cmake.org/cmake/help/v3.14/module/FindBLAS.html#result-variables
> build(cmake): enable language C to use MKL as BLAS

- src/dftd4/api.f90
- src/dftd4/charge.f90
- src/dftd4/cutoff.f90
- src/dftd4/damping/rational.f90
- src/dftd4/data/covrad.f90
- src/dftd4/data/en.f90
- src/dftd4/disp.f90
- src/dftd4/model.f90
- src/dftd4/ncoord.f90
- src/dftd4/output.f90
- src/dftd4/param.f90
- src/dftd4/utils.f90
- src/dftd4/version.f90
* Exports must be explictly declared for the MSVC compiler. This commit adds DLLEXPORT attributes to the subroutines needed for the api and app to compile
Signed-off-by: Ty <ty.balduf@schrodinger.com>
This still the same pull request as https://github.com/dftd4/dftd4/pull/168. Had to remake due to clunky choice of branching
> Export API routines for MSVC compiler

- CMakeLists.txt
- config/CMakeLists.txt
- config/meson.build
- meson_options.txt
- src/dftd4/CMakeLists.txt
- src/dftd4/blas.F90
- src/dftd4/meson.build
Adds support for BLAS/LAPACK ILP64.
`cmake`:  `-DWITH_ILP64` **and** `DBLAS_LIBRARIES` 
`meson`: `Dilp64=true`
Note that `multicharge` must also have `ILP64` support (grimme-lab/multicharge#16)
> ILP64 support

- .github/workflows/fortran-build.yml
- assets/ci/build-env.yaml
- assets/ci/python-env.yaml
- assets/ci/setup-intel.sh
Using conda environments to provision the dependencies for CI testing seems more stable than using the base images.
> Provision CI from conda-forge

- python/dftd4/pyscf.py
- python/dftd4/test_pyscf.py
Allows to correctly print PySCF the dispersion contribution from a `mf` object.
See See https://github.com/pyscf/pyscf/blob/8b3fef8cf18f10d430261d4a8bea21fadf19bb1f/pyscf/scf/hf.py#L1054-L1076.
Closes #192 
Requires #194
> PySCF: Capture dispersion energy in scf_summary

- src/dftd4/param.f90
Applying the suggestions from #201.
> Replace merge statements for optional parameters

- python/dftd4/pyscf.py
- python/dftd4/test_pyscf.py
- use atomic symbols and [pyscf's charge function](https://github.com/pyscf/pyscf/blob/bf0b1db22556a3c1b4c34426ea8627e636c1b096/pyscf/data/elements.py#L1136) for obtaining atomic numbers
> Fix passing atomic numbers from PySCF to D4 interface

- config/meson.build
These changes ensure that the Intel LLVM compiler is treated as the standard Intel compiler, addressing specific compatibility issues we've encountered.
> Treat Intel LLVM compiler as standard Intel compiler (#252)

- README.md
- doc/recipe/vasp.rst
See #216. As suggested by https://github.com/dftd4/dftd4/issues/216#issuecomment-2632529681.
> Update VASP linking instructions

- README.md
- doc/recipe/vasp.rst
Revert #279 because instructions failed for other users. Only add hint if linking fails.
> Update VASP build instructions

- .github/workflows/fortran-build.yml
Older versions always pull the latest fpm version, which now breaks after compiler name was added to the release artifacts (see https://github.com/fortran-lang/fpm/issues/1104).
> Bump setup-fpm to v7

- .github/workflows/fortran-build.yml
Ubuntu 20.04 runners are discontinued and GCC8 is not on 22.04 anymore.
> Replace Ubuntu 20.04 with 22.04

- python/dftd4/parameters.py
The Windows fix #268 has a small typo that produces confusing results :-)
All the tests really do pass (see 84e3c1bf7548d8faf45d34aff4333428e5d84a51). I'm having trouble getting them all passing at once.
> fix accessing parameters in windows

- app/driver.f90
- src/dftd4/disp.f90
- src/dftd4/output.f90
Print static polarizability in properties. Before, it was calculated but not passed to the `ascii_system_properties` procedure. To be exact, the static polarizability is the imaginary frequency polarizability `alpha(iw)` at w=1e-6.
> Print static polarizability
